# Uncomment the next line to define a global platform for your project
platform :osx, '10.10'

target 'QVKeyboardClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Update
  pod 'Sparkle'


end
