# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'QVKeyboard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QVKeyboard
  pod 'Masonry'

end

target 'QVKeyboardApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QVKeyboardApp
  pod 'Masonry'
  pod 'Toast'

end
